
const data = [
    {
    id: 1,
    caseNumber: 'GGJDH89DSJ', 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    applicationDate: '04/04/22023',
    update: '04/04/22023',      
    status: 'Pending',
    appStatus: 'Docs. Reviewed',
    pending: 'Pending',
    active: 'Active',
    due: 'Due for payment',
    extend: 'Extended',
    default: 'Defaulted',
    close: 'Closed',
},
{
    id: 2,
    caseNumber: 'GGJDH89DSJ', 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    applicationDate: '04/04/22023',
    update: '04/04/22023',       
    status: 'Approved',
    appStatus: 'Approved',
    pending: 'Pending',
    active: 'Active',
    due: 'Due for payment',
    extend: 'Extended',
    default: 'Defaulted',
    close: 'Closed',
},
{
    id: 3,
    caseNumber: 'GGJDH89DSJ', 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    applicationDate: '04/04/22023',
    update: '04/04/22023',       
    status: 'Closed',
    appStatus: 'Declined',
    pending: 'Pending',
    active: 'Active',
    due: 'Due for payment',
    extend: 'Extended',
    default: 'Defaulted',
    close: 'Closed',
},
{
    id: 4,
    caseNumber: 'GGJDH89DSJ', 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    applicationDate: '04/04/22023',
    update: '04/04/22023',       
    status: 'Due',
    appStatus: 'Docs. Reviewed',
    pending: 'Pending',
    active: 'Active',
    due: 'Due for payment',
    extend: 'Extended',
    default: 'Defaulted',
    close: 'Closed',
},
{
    id: 5,
    caseNumber: 'GGJDH89DSJ', 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    applicationDate: '04/04/22023',
    update: '04/04/22023',       
    status: 'Approved',
    appStatus: 'Incomplete Docs.',
    pending: 'Pending',
    active: 'Active',
    due: 'Due for payment',
    extend: 'Extended',
    default: 'Defaulted',
    close: 'Closed',
},
{
    id: 6,
    caseNumber: 'GGJDH89DSJ', 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    applicationDate: '04/04/22023',
    update: '04/04/22023',       
    status: 'Approved',
    appStatus: 'Approved',
    pending: 'Pending',
    active: 'Active',
    due: 'Due for payment',
    extend: 'Extended',
    default: 'Defaulted',
    close: 'Closed',
},
{
    id: 7,
    caseNumber: 'GGJDH89DSJ', 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    applicationDate: '04/04/22023',
    update: '04/04/22023',       
    status: 'Declined',
    appStatus: 'Docs. Reviewed',
    pending: 'Pending',
    active: 'Active',
    due: 'Due for payment',
    extend: 'Extended',
    default: 'Defaulted',
    close: 'Closed',
},
{
    id: 8,
    caseNumber: 'GGJDH89DSJ', 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    applicationDate: '04/04/22023',
    update: '04/04/22023',       
    status: 'Approved',
    appStatus: 'Incomplete Docs.',
    pending: 'Pending',
    active: 'Active',
    due: 'Due for payment',
    extend: 'Extended',
    default: 'Defaulted',
    close: 'Closed',
},
]

export default data;