 
const setdata = [
{
    id: 1, 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    Email: 'paschodes@gmail.com',
    Role: 'Loan Officer',
    status: 'Approver',
    action: 'choose',
},
{
    id: 2,
    firstName: 'Temidayo',
    LastName: 'Adebayo',      
    Email: 'paschodes@gmail.com',
    Role: 'Manager',
    status: 'Reviewer',
    action: 'choose',
},
{
    id: 3,
    firstName: 'Temidayo',
    LastName: 'Adebayo',     
    Email: 'paschodes@gmail.com',
    Role: 'Supervisor',
    status: 'Reviewer',
    action: 'choose',
},
{
    id: 4,
    firstName: 'Temidayo',
    LastName: 'Adebayo',     
    status: 'Due',
    Email: 'paschodes@gmail.com',
    Role: 'Field Officer',
    status: 'Uploader',
    action: 'choose',
},
{
    id: 5, 
    firstName: 'Temidayo',
    LastName: 'Adebayo',
    Email: 'paschodes@gmail.com',
    Role: 'Loan Officer',
    status: 'Approver',
    action: 'choose',
},
{
    id: 6,
    firstName: 'Temidayo',
    LastName: 'Adebayo',      
    Email: 'paschodes@gmail.com',
    Role: 'Manager',
    status: 'Reviewer',
    action: 'choose',
},
{
    id: 7,
    firstName: 'Temidayo',
    LastName: 'Adebayo',     
    Email: 'paschodes@gmail.com',
    Role: 'Supervisor',
    status: 'Reviewer',
    action: 'choose',
},
{
    id: 8,
    firstName: 'Temidayo',
    LastName: 'Adebayo',     
    Email: 'paschodes@gmail.com',
    Role: 'Field Officer',
    status: 'Uploader',
    action: 'choose',
},
]

export default setdata;